#!/bin/bash

##DOC: Generation of selenium files
##DOC:

##DOC: batchOpen <base_url> <file> (pause): Create test to access the resources defined in the file
function batchOpen() {
local line
IFS="
"

  if [ $# -lt 2 ]; then
    echo "ERROR: two parameters expected"
    return 255
  fi

  beginDoc $1
  for line in `cat $2`; do
    beginLine
    addParam "open"
    addParam $line
    addParam ""
    endLine
    if [ $# -eq 3 ]; then 
      beginLine
      addParam "pause"
      addParam ""
      addParam $3
      endLine
    fi
  done
  endDoc
}


function beginLine() { # Internal
  echo "  <tr>"
}

function endLine() { # Internal
  echo "  </tr>"
}

function addParam() { # Internal
  echo "    <td>$*</td>"
}

function beginDoc() { # Internal
  cat << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="$1" />
<title>tmp</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">tmp</td></tr>
</thead><tbody>
EOF
}

function endDoc() { # Internal
  cat << EOF
</tbody></table>
</body>
</html>
EOF
}
